const db = require("../config/db");
const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// ================================
// Prosecutor Dashboard
// ================================
exports.dashboard = async (req, res) => {
    try {
        const [cases] = await db.execute(`
            SELECT e.*, u.username AS investigator
            FROM evidence e
            JOIN users u ON e.collected_by = u.user_id
            WHERE e.current_status='completed'
            ORDER BY e.timestamp_collected DESC
        `);

        res.render("prosecutor/dashboard", { cases });
    } catch (err) {
        console.error(err);
        res.status(500).send("Error loading cases");
    }
};

// ================================
// View Case 
// ================================
exports.viewCase = async (req, res) => {
    const { id } = req.params;

    const [evidence] = await db.execute(
        "SELECT * FROM evidence WHERE evidence_id=?",
        [id]
    );

    const [chain] = await db.execute(
        "SELECT * FROM evidence_chain WHERE evidence_id=? ORDER BY block_id ASC",
        [id]
    );

    const [report] = await db.execute(
        "SELECT * FROM forensic_reports WHERE evidence_id=?",
        [id]
    );

    res.render("prosecutor/viewCase", {
        evidence: evidence[0],
        chain,
        report: report[0]
    });
};

exports.exportChainPDF = async (req, res) => {
    try {
        const { id } = req.params;
        const userId = req.session.user.user_id;

        // ================================
        // 1️. Fetch evidence
        // ================================
        const [evidenceRows] = await db.execute(
            "SELECT * FROM evidence WHERE evidence_id=?",
            [id]
        );
        const evidence = evidenceRows[0];

        // ================================
        // 2️. Fetch chain of custody
        // ================================
        const [chain] = await db.execute(
            "SELECT ec.*, u.username FROM evidence_chain ec JOIN users u ON ec.actor_id=u.user_id WHERE evidence_id=? ORDER BY block_id ASC",
            [id]
        );

        // ================================
        // 3️. Fetch forensic report
        // ================================
        const [reportRows] = await db.execute(
            "SELECT * FROM forensic_reports WHERE evidence_id=?",
            [id]
        );
        const report = reportRows[0];

        // ================================
        // 4️. Create PDF
        // ================================
        const doc = new PDFDocument();
        const fileName = `Chain_of_Custody_${evidence.case_id}.pdf`;
        const filePath = path.join(__dirname, "../public/reports", fileName);

        doc.pipe(fs.createWriteStream(filePath));

        // ================================
        // PDF CONTENT 
        // ================================
        doc.fontSize(18).text("CHAIN OF CUSTODY REPORT", { align: "center" });
        doc.moveDown();

        doc.fontSize(12).text(`Case ID: ${evidence.case_id}`);
        doc.text(`Evidence Description: ${evidence.description}`);
        doc.text(`Current Status: ${evidence.current_status}`);
        doc.text(`Initial Hash: ${evidence.initial_hash}`);
        doc.text(`Final Hash: ${evidence.final_hash || "N/A"}`);
        doc.moveDown();

        doc.fontSize(14).text("Chain of Custody Log:");
        doc.moveDown();

        chain.forEach((c, index) => {
            doc.fontSize(11).text(
                `${index + 1}. ${c.action}
Actor: ${c.username}
Timestamp: ${new Date(c.timestamp).toLocaleString()}
Hash: ${c.data_hash}
Previous Hash: ${c.previous_hash || "—"}
`
            );
            doc.moveDown();
        });

        if (report) {
            doc.addPage();
            doc.fontSize(14).text("Forensic Report Summary");
            doc.moveDown();
            doc.fontSize(11).text(`Report File: ${report.report_file_path}`);
            doc.text(`Report Hash: ${report.report_hash}`);
            doc.text(`Uploaded At: ${new Date(report.uploaded_at).toLocaleString()}`);
        }

        doc.addPage();
        doc.fontSize(10).text(
            "This document is generated by a Blockchain-Based Chain of Custody Management System. " +
            "All custody records are logged with cryptographic hashes to ensure integrity and compliance " +
            "with Malaysian forensic SOPs and Evidence Act 1950.",
            { align: "justify" }
        );

        doc.end();

        // ================================
        // 5. Audit log
        // ================================
        await db.execute(
            "INSERT INTO audit_logs (user_id, action, user_ip_address, details) VALUES (?, ?, ?, ?)",
            [userId, "Exported Chain of Custody PDF", req.ip, `Evidence ID ${id}`]
        );

        // ================================
        // 6. Download
        // ================================
        res.download(filePath);

    } catch (err) {
        console.error(err);
        res.status(500).send("PDF generation failed");
    }
};